#source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :generate_multiple_pod_projects => true

platform :ios, '10.0'
use_frameworks!

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'Lantern', :path => '../'
  pod 'SDWebImage'
  pod 'Kingfisher'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         end
    end
  end
end
