source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :generate_multiple_pod_projects => true

platform :ios, '10.0'
use_frameworks!

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'Lantern', :path => '../'
  pod 'SDWebImage'
  pod 'Kingfisher'
end
